lots of errors in download script

diff --git a/roles/osm-vector-maps/files/install-map-region b/roles/osm-vector-maps/files/install-map-region
--- a/roles/osm-vector-maps/files/install-map-region
+++ b/roles/osm-vector-maps/files/install-map-region
@@ -1,6 +1,7 @@
 #!/bin/bash -x
 # fetch the specified tileset or world to zoom 10 without Admin Console
 
+source_url=https://archive.org/download
 SATELLITE=$source_url/satellite_z0-z9_v3.mbtiles/satellite_z0-z9_v3.mbtiles
 working_dir=/library/working/maps
 PLANET=https://archive.org/download/osm-planet_z0-z10_2019.mbtiles/osm-planet_z0-z10_2019.mbtiles
@@ -9,24 +10,32 @@ SAN_JOSE=https://archive.org/download/san_jose_z11-z14_2019.mbtiles/san_jose_z11
 # If called without a parameter (perhaps from ansible), just load world to zoom 10
 if [ $# -eq 0 ]; then
    TILESET=$SAN_JOSE
+   PROGRESS=""
+   fn=$(basename $SAN_JOSE)
+   if [ ! -f /library/www/osm-vector-maps/viewer/tiles/$fn ];then
+      wget -c $source_url/$SAN_JOSE/$SAN_JOSE $PROGRES -P $working_dir
+   fi
+   if [ $? -ne 0 ]; then
+      echo "Download of $fn failed. Please retry download command"
+      exit 1
+   fi
 else
    TILESET=$1
    PROGRESS="--progress=dot:giga"
+   fn=$(basename $1)
+   if [ ! -f /library/www/osm-vector-maps/viewer/tiles/$fn ];then
+      wget -c $source_url/$1/$1 $PROGRES -P $working_dir
+   fi
+   if [ $? -ne 0 ]; then
+      echo "Download of $fn failed. Please retry download command"
+      exit 1
+   fi
 fi
 
 # get the data for planet to zoom 10, satellite to zoom 9, and san_jose to zoom 14
 fn=$(basename $SATELLITE)
 if [ ! -f /library/www/osm-vector-maps/viewer/tiles/$fn ];then
-   wget -c $SATELLITE $PROGRES -P $working_dir
-fi
-if [ $? -ne 0 ]; then
-   echo "Download of $fn failed. Please retry download command"
-   exit 1
-fi
-
-fn=$(basename $SAN_JOSE)
-if [ ! -f /library/www/osm-vector-maps/viewer/tiles/$fn ];then
-   wget -c $SAN_JOSE $PROGRES -P $working_dir
+   wget -c $source_url/$SATELLITE/$SATELLITE $PROGRES -P $working_dir
 fi
 if [ $? -ne 0 ]; then
    echo "Download of $fn failed. Please retry download command"
@@ -35,7 +44,7 @@ fi
 
 fn=$(basename $PLANET)
 if [ ! -f /library/www/osm-vector-maps/viewer/tiles/$fn ];then
-   wget -c $san_jose2z14 $PROGRES -P $working_dir
+   wget -c $source_url/$PLANET/$PLANET $PROGRES -P $working_dir
 fi
 if [ $? -ne 0 ]; then
    echo "Download of $fn failed. Please retry download command"
