Update iiab-mongodb-repair-if-no-lock.j2

diff --git a/roles/mongodb/templates/iiab-mongodb-repair-if-no-lock.j2 b/roles/mongodb/templates/iiab-mongodb-repair-if-no-lock.j2
--- a/roles/mongodb/templates/iiab-mongodb-repair-if-no-lock.j2
+++ b/roles/mongodb/templates/iiab-mongodb-repair-if-no-lock.j2
@@ -3,5 +3,5 @@
 if [ ! -f {{ mongodb_db_lock_file }} ]; then
     /usr/bin/mongod --repair --dbpath {{ mongodb_db_path }}
 else
-    echo '"mongod --repair" cannot run when {{ mongodb_db_lock_file }} present.'
+    echo '"mongod --repair" cannot run when {{ mongodb_db_lock_file }} present.' >&2    # Output to STDERR but keep going, so /etc/systems/system/mongodb.service continues
 fi
