Highlight error in red, if /opt/iiab/iiab missing (and needed)

diff --git a/iiab-support b/iiab-support
--- a/iiab-support
+++ b/iiab-support
@@ -65,7 +65,7 @@ else
         # Above is tighter/better than running all of "./runrole 1-prep"
         echo
     else
-        echo -e 'Directory /opt/iiab/iiab does not exist: CANNOT INSTALL OPENVPN!\n'
+        echo -e '\e[41m       Directory /opt/iiab/iiab does not exist: CANNOT INSTALL OPENVPN!       \e[0m\n'
         exit 1
     fi
 fi
@@ -116,4 +116,5 @@ if [ "$vpnip" != "" ]; then
     echo -e "\nYour OpenVPN IP address (which can change) is: \e[32m$vpnip\e[0m\n"
 else
     echo -e "\n \e[41m       ERROR: OpenVPN IP address not ready - PLEASE TRY THE ABOVE TIPS        \e[0m\n"
+    exit 1
 fi
