Exit w/ explanation if /opt/iiab/iiab was deleted

diff --git a/iiab-support b/iiab-support
--- a/iiab-support
+++ b/iiab-support
@@ -55,17 +55,19 @@ else
     else
         echo "openvpn_install: True" >> /etc/iiab/local_vars.yml
     fi
-    #cd /opt/iiab/iiab
-    #./runrole 1-prep
-
-    #CWD=`pwd`
-    #export ANSIBLE_LOG_PATH="$CWD/iiab-install.log"
-
-    # For log file, in case git tree deleted, on IIABs with very small disks:
-    mkdir -p /opt/iiab/iiab    
-    export ANSIBLE_LOG_PATH="/opt/iiab/iiab/iiab-install.log"
-    ansible-playbook -i $INVENTORY $PLAYBOOK --connection=local
-    echo
+    
+    if [ -d /opt/iiab/iiab ]; then
+        cd /opt/iiab/iiab
+        #CWD=`pwd`
+        #export ANSIBLE_LOG_PATH="$CWD/iiab-install.log"
+        export ANSIBLE_LOG_PATH="/opt/iiab/iiab/iiab-install.log"
+        ansible-playbook -i $INVENTORY $PLAYBOOK --connection=local
+        # Above is tighter/better than running all of "./runrole 1-prep"
+        echo
+    else
+        echo -e 'Directory /opt/iiab/iiab does not exist: CANNOT INSTALL OPENVPN!\n'
+        exit 1
+    fi
 fi
 
 echo -e "Now let's (re)enable OpenVPN...\n"
