double-double-quote vars in echo for safety etc

diff --git a/iiab-install b/iiab-install
--- a/iiab-install
+++ b/iiab-install
@@ -31,7 +31,7 @@ if [ ! -f /etc/iiab/local_vars.yml ]; then
     echo -e "(2) MIN/MEDIUM/BIG samples are included in /opt/iiab/iiab/vars" >&2
     echo -e "(3) NO TIME FOR DETAILS?  RUN INTERNET-IN-A-BOX'S FRIENDLY 1-LINE INSTALLER:\n" >&2
 
-    echo -e '    http://download.iiab.io   (click on "7.0" or a more recent version!)\n' >&2
+    echo -e '    http://download.iiab.io\n' >&2
 
     exit 1
 fi
@@ -47,8 +47,8 @@ cp ./scripts/local_facts.fact /etc/ansible/facts.d/local_facts.fact
 echo "Placed /etc/ansible/facts.d/local_facts.fact into position."
 
 if [ ! -f $PLAYBOOK ]; then
-    echo "EXITING: IIAB Playbook not found."
-    echo "Please run 'iiab-install' from /opt/iiab/iiab (top level of git repo)."
+    echo "EXITING: IIAB Playbook ""$PLAYBOOK"" not found."
+    echo "Please run './iiab-install' from /opt/iiab/iiab (top level of git repo)."
     exit 1
 fi
 
@@ -152,6 +152,7 @@ fi
 
 # Assumes /etc/iiab/iiab_state.yml is not created until (prior run of) Stage 4.
 if [ -f $IIAB_STATE_FILE ]; then
+    # Workaround for (web-published) images; will go away later
     if grep -q sugar $IIAB_STATE_FILE; && ! grep -q mongodb $IIAB_STATE_FILE; then
         echo "mongodb_installed: True" >> $IIAB_STATE_FILE
     fi
