bail early if playbook not found

diff --git a/iiab-install b/iiab-install
--- a/iiab-install
+++ b/iiab-install
@@ -12,6 +12,13 @@ OS=${OS//\"/}
 
 export ANSIBLE_LOG_PATH="$CWD/iiab-install.log"
 
+if [ ! -f $PLAYBOOK ]; then
+    echo "IIAB Playbook not found."
+    echo "Please run this command from the top level of the git repo."
+    echo "Exiting."
+    exit 1
+fi
+
 if [ $OS = "raspbian" ]; then
     echo "found"
     REBOOT=`uname -a | grep 4.9.59-v7+ | wc -l`
@@ -56,13 +63,6 @@ else
             exit 1
         fi
     fi
-fi
-
-if [ ! -f $PLAYBOOK ]; then
-    echo "IIAB Playbook not found."
-    echo "Please run this command from the top level of the git repo."
-    echo "Exiting."
-    exit 1
 fi
 
 # if vars/local_vars.yml is missing, put a default one in place - First Run
