double-double-quote vars in echo for safety etc

diff --git a/iiab-install b/iiab-install
--- a/iiab-install
+++ b/iiab-install
@@ -31,7 +31,7 @@ if [ ! -f /etc/iiab/local_vars.yml ]; then
     echo -e "(2) MIN/MEDIUM/BIG samples are included in /opt/iiab/iiab/vars" >&2
     echo -e "(3) NO TIME FOR DETAILS?  RUN INTERNET-IN-A-BOX'S FRIENDLY 1-LINE INSTALLER:\n" >&2
 
-    echo -e '    http://download.iiab.io   (click on "7.0" or a more recent version!)\n' >&2
+    echo -e '    http://download.iiab.io\n' >&2
 
     exit 1
 fi
@@ -47,8 +47,8 @@ cp ./scripts/local_facts.fact /etc/ansible/facts.d/local_facts.fact
 echo "Placed /etc/ansible/facts.d/local_facts.fact into position."
 
 if [ ! -f $PLAYBOOK ]; then
-    echo "EXITING: IIAB Playbook not found."
-    echo "Please run 'iiab-install' from /opt/iiab/iiab (top level of git repo)."
+    echo "EXITING: IIAB Playbook ""$PLAYBOOK"" not found."
+    echo "Please run './iiab-install' from /opt/iiab/iiab (top level of git repo)."
     exit 1
 fi
 
@@ -70,9 +70,9 @@ version_gt() { [ "$(printf '%s\n' "$@" | sort -V | head -1)" != "$1" ]; }
 # Verify that Raspbian is running a recent enough kernel.  As Raspbian
 # updates on 4.9.41-v7+ broke bridging, WiFi AP & OpenVPN in Oct/Nov 2017.
 CURR_KERN=`uname -r`
-echo "Found Kernel "$CURR_KERN""
+echo "Found Kernel ""$CURR_KERN"
 if [ "$OS" == "raspbian" ] && version_gt $MIN_RPI_KERN $CURR_KERN ; then
-    echo -e "\nEXITING: Kernel "$MIN_RPI_KERN" or higher required with Raspbian."
+    echo -e "\nEXITING: Kernel ""$MIN_RPI_KERN"" or higher required with Raspbian."
     echo -e "PLEASE RUN 'apt update' then 'apt install raspberrypi-kernel' then reboot."
     echo -e "IIAB INSTALL INSTRUCTIONS: https://github.com/iiab/iiab/wiki/IIAB-Installation"
     exit 1
@@ -91,10 +91,10 @@ if [[ `command -v ansible` ]]; then        # "command -v" is POSIX compliant; it
     #CURR_ANSIBLE_VER=`ansible --version | head -1 | sed -e 's/.* //'`
     #CURR_ANSIBLE_VER=`ansible --version | head -1 | cut -f 2 -d " "`
     CURR_ANSIBLE_VER=`ansible --version | head -1 | awk '{print $2}'`    # to match scripts/ansible
-    echo "Found Ansible "$CURR_ANSIBLE_VER""
+    echo "Found Ansible ""$CURR_ANSIBLE_VER"
 fi
 if version_gt $MIN_ANSIBLE_VER $CURR_ANSIBLE_VER ; then
-    echo -e "\nEXITING: Ansible "$MIN_ANSIBLE_VER" or higher required.\n"
+    echo -e "\nEXITING: Ansible ""$MIN_ANSIBLE_VER"" or higher required.\n"
 
     echo -e "REMOVE PRIOR VERSIONS using 'apt purge ansible' and/or 'pip uninstall ansible'."
     echo -e "THEN RUN 'scripts/ansible' to install the latest Ansible from PPA or RPM."
@@ -112,17 +112,17 @@ if [ -f /etc/iiab/iiab.env ]; then
         source /etc/iiab/iiab.env
         echo "Extracted STAGE=$STAGE (counter) from /etc/iiab/iiab.env"
         if ! [ "$STAGE" -eq "$STAGE" ] 2> /dev/null; then
-            echo -e "\nEXITING: STAGE (counter) value == $STAGE is non-integer in /etc/iiab/iiab.env"
+            echo -e "\nEXITING: STAGE (counter) value == ""$STAGE"" is non-integer in /etc/iiab/iiab.env"
             exit 1
         elif [ "$STAGE" -lt 0 ] || [ "$STAGE" -gt 9 ]; then
-            echo -e "\nEXITING: STAGE (counter) value == $STAGE is out-of-range in /etc/iiab/iiab.env"
+            echo -e "\nEXITING: STAGE (counter) value == ""$STAGE"" is out-of-range in /etc/iiab/iiab.env"
             exit 1
         fi
     fi
 
     if [ "$1" == "--reinstall" ]; then
         STAGE=0
-        ARGS="$ARGS --extra-vars reinstall=True"
+        ARGS="$ARGS"" --extra-vars reinstall=True"
         sed -i 's/^STAGE=.*/STAGE=0/' /etc/iiab/iiab.env
         echo "Wrote STAGE=0 (counter) to /etc/iiab/iiab.env"
     elif [ "$STAGE" -ge 2 ] && [ "$1" == "--debug" ]; then
@@ -151,6 +151,7 @@ fi
 
 # Assumes /etc/iiab/iiab_state.yml is not created until (prior run of) Stage 4.
 if [ -f $IIAB_STATE_FILE ]; then
+    # Workaround for (web-published) images; will go away later
     if grep -q sugar $IIAB_STATE_FILE; && ! grep -q mongodb $IIAB_STATE_FILE; then
         echo "mongodb_installed: True" >> $IIAB_STATE_FILE
     fi
@@ -168,7 +169,7 @@ echo -e "\nTRY TO RERUN './iiab-install' IF IT FAILS DUE TO CONNECTIVITY ISSUES 
 
 echo -e "Running local Ansible playbooks...\n...Stage 0 will now run\n...followed by Stages $(($STAGE + 1))-9\n...and then the Network Role.\n"
 
-export ANSIBLE_LOG_PATH="$CWD/iiab-install.log"
+export ANSIBLE_LOG_PATH="$CWD""/iiab-install.log"
 
 ansible -m setup -i $INVENTORY localhost --connection=local | grep python
 ansible -m setup -i $INVENTORY localhost --connection=local >> /dev/null    # So vars are recorded in /opt/iiab/iiab/iiab-install.log
