Update iiab-install

diff --git a/iiab-install b/iiab-install
--- a/iiab-install
+++ b/iiab-install
@@ -18,6 +18,13 @@ if [ ! -f /etc/iiab/local_vars.yml ]; then
     echo -e "(2) MIN/MEDIUM/BIG samples are included in /opt/iiab/iiab/vars" >&2
     echo -e "(3) NO TIME FOR DETAILS?  RUN INTERNET-IN-A-BOX'S FRIENDLY 1-LINE INSTALLER:\n" >&2
     echo -e '    http://download.iiab.io   (click on "6.6" or a more recent version!)\n' >&2
+
+    if [ -f /opt/iiab/iiab/vars/local_vars.yml ]; then
+        echo -e "\nACTION REQUIRED: /opt/iiab/iiab/vars/local_vars.yml IS NO LONGER SUPPORTED.\n" >&2
+        echo -e "To move it to the correct location, run:\n" >&2
+        echo -e "    mv /opt/iiab/iiab/vars/local_vars.yml /etc/iiab/local_vars.yml" >&2
+    fi
+
     #case $OS in
     #    OLPC | fedora)
     #        echo -e "Please examine /opt/iiab/iiab/vars/local_vars_olpc.yml for XO laptops.\n" >&2
