runrole - ensure local_vars has *_install is set to True

diff --git a/runrole b/runrole
--- a/runrole
+++ b/runrole
@@ -3,8 +3,11 @@
 INVENTORY="ansible_hosts"
 PLAYBOOK="run-one-role.yml"
 ARGS=""
+REINSTALL=0
 CWD=`pwd`
 APPS=/etc/iiab/config_vars2.yml
+VARS=/etc/iiab/local_vars.yml
+
 if [ ! -f $PLAYBOOK ]; then
     echo "Exiting: IIAB Playbook not found."
     echo "Please run this in /opt/iiab/iiab (top level of the git repo)."
@@ -19,27 +22,57 @@ if [[ $# -eq 0 ]] ; then
     exit 0
 fi
 
+clear_marker(){
+    if [ ! $1 == "internetarchive" ]; then # special handling
+        if [ $1 == "calibre-web" ]; then # role directory & installed marker differ
+            sed -i -e '/^calibreweb/d' $APPS
+
+        elif [ $1 == "captive-portal" ]; then # role directory & installed marker differ
+            sed -i -e '/^captiveportal/d' $APPS
+
+        elif [ $1 == "bluetooth" ]; then # role directory & installed marker differ
+            sed -i -e '/^pan_bluetooth/d' $APPS
+        fi
+        sed -i -e "/^$1/d" $APPS
+    fi
+}
+
+if [ "$1" == "--reinstall" ]; then
+    ARGS="$ARGS --extra-vars reinstall=True"
+    REINSTALL=1
+    shift 1
+fi
+
 # needed for stage 1-3 if not installed yet
 if [ ! -f $APPS ]; then
     mkdir -p /etc/iiab
     touch $APPS
 fi
 
-if [ "$1" == "--reinstall" ]; then
-    ARGS="$ARGS --extra-vars reinstall=True"
-    if [ ! $2 == "internetarchive" ]; then # special handling
-        if [ $2 == "calibre-web" ]; then # role directory & installed marker differ
-            sed -i -e '/^calibreweb/d' $APPS
-        fi
-        if [ $2 == "captive-portal" ]; then # role directory & installed marker differ
-            sed -i -e '/^captiveportal/d' $APPS
-        fi
-        if [ $2 == "bluetooth" ]; then # role directory & installed marker differ
-            sed -i -e '/^pan_bluetooth/d' $APPS
-        fi
-        sed -i -e "/^$2/d" $APPS
+if ! grep -q $1_install $VARS; then
+    echo " $1_install: not found in $VARS"
+    echo " Please review $VARS and edit as required"
+    exit 1
+elif grep $1_install $VARS | grep -q --exclude "#" False; then
+    echo " $1_install: set to False found in $VARS"
+    echo " Please review $VARS and edit as required"
+    exit 1
+elif grep $1_install $VARS | grep -q "#"; then
+    echo " $1_install: commented out (#) in $VARS"
+    echo " Please review $VARS and edit as required"
+    exit 1
+else
+    if grep $1_install $VARS | grep -q --exclude "#" True; then
+        echo " $1_install: set to True found in $VARS"
+        echo " continuing...."
+    else
+        echo "somthing went wrong to get here"
+        exit 1
     fi
-    shift 1
+fi
+
+if [ "$REINSTALL" == "1" ]; then
+    clear_marker
 fi
 
 if [ $# -eq 2 ]; then
