Untabify: indentation is better as spaces not tabs

diff --git a/runrole b/runrole
--- a/runrole
+++ b/runrole
@@ -60,23 +60,23 @@ fi
 echo
 if $REINSTALL; then   # Add '_' so '--reinstall calibre' doesn't zap calibreweb
     if grep -q "^${ROLE_VAR}_" $IIAB_STATE_FILE; then
-	echo -e "\e[1mThese line(s) in $IIAB_STATE_FILE are now being deleted:\e[0m\n"
-	grep "^${ROLE_VAR}_" $IIAB_STATE_FILE; echo
-	sed -i "/^${ROLE_VAR}_/d" $IIAB_STATE_FILE
+        echo -e "\e[1mThese line(s) in $IIAB_STATE_FILE are now being deleted:\e[0m\n"
+        grep "^${ROLE_VAR}_" $IIAB_STATE_FILE; echo
+        sed -i "/^${ROLE_VAR}_/d" $IIAB_STATE_FILE
     else
-	echo -e "\e[1mERROR: $IIAB_STATE_FILE has no lines that begin with '${ROLE_VAR}_'\e[0m\n"
-	echo -e "Try again without the '--reinstall' flag?\n"
-	exit 1
+        echo -e "\e[1mERROR: $IIAB_STATE_FILE has no lines that begin with '${ROLE_VAR}_'\e[0m\n"
+        echo -e "Try again without the '--reinstall' flag?\n"
+        exit 1
     fi
 else
     if grep -q "^${ROLE_VAR}_" $IIAB_STATE_FILE; then
         echo -e "\e[1mWARNING: $IIAB_STATE_FILE already has this/these line(s):\e[0m\n"
-	grep "^${ROLE_VAR}_" $IIAB_STATE_FILE; echo
+        grep "^${ROLE_VAR}_" $IIAB_STATE_FILE; echo
         echo -e "To reinstall it, run: ./runrole --reinstall $1\n"
-	echo -n "Or continue, e.g. to enable/disable it based on var '${ROLE_VAR}_enabled' ? [Y/n] "
-	read ans < /dev/tty
-	echo
-	[ "$ans" = "n" ] || [ "$ans" = "N" ] &&
+        echo -n "Or continue, e.g. to enable/disable it based on var '${ROLE_VAR}_enabled' ? [Y/n] "
+        read ans < /dev/tty
+        echo
+        [ "$ans" = "n" ] || [ "$ans" = "N" ] &&
             exit 1
     fi
 fi
