remove installed check

diff --git a/roles/remoteit/templates/iiab-remoteit b/roles/remoteit/templates/iiab-remoteit
--- a/roles/remoteit/templates/iiab-remoteit
+++ b/roles/remoteit/templates/iiab-remoteit
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-# Run 'sudo iiab-remoteit' to turn on remoteit without hassle.  GENERAL TIPS:
+# Run 'sudo iiab-remoteit' to (re)install remoteit without hassle.  GENERAL TIPS:
 # http://FAQ.IIAB.IO -> "How can I remotely manage my Internet-in-a-Box?"
 
 echo -e "Now let's (re)enable remoteit...\n"
@@ -10,22 +10,18 @@ else
     echo "remoteit_enabled: True" >> /etc/iiab/local_vars.yml
 fi
 
-if grep -q '^remoteit_installed:\s\+[tT]rue\b' /etc/iiab/iiab_state.yml; then
-    echo -e "Your IIAB installation appears normal, with remoteit already installed...\n"
+echo -e "Plz wait a few minutes as remoteit is confirmed/installed...\n"
+if grep -q '^remoteit_install:' /etc/iiab/local_vars.yml; then
+    sed -i "s/^remoteit_install:.*/remoteit_install: True/" /etc/iiab/local_vars.yml
 else
-    echo -e "Plz wait a few minutes as remoteit is confirmed/installed...\n"
-    if grep -q '^remoteit_install:' /etc/iiab/local_vars.yml; then
-        sed -i "s/^remoteit_install:.*/remoteit_install: True/" /etc/iiab/local_vars.yml
-    else
-        echo "remoteit_install: True" >> /etc/iiab/local_vars.yml
-    fi
+    echo "remoteit_install: True" >> /etc/iiab/local_vars.yml
+fi
 
-    if [ -d /opt/iiab/iiab ]; then
-        cd /opt/iiab/iiab
-        ./runrole remoteit
-        echo
-    else
-        echo -e " \e[41;1m       Directory /opt/iiab/iiab does not exist: CANNOT INSTALL OPENVPN!       \e[0m\n"
-        exit 1
-    fi
+if [ -d /opt/iiab/iiab ]; then
+    cd /opt/iiab/iiab
+    ./runrole remoteit
+    echo
+else
+    echo -e " \e[41;1m       Directory /opt/iiab/iiab does not exist: CANNOT INSTALL REMOTEIT!       \e[0m\n"
+    exit 1
 fi
