Weird indenting

diff --git a/roles/maps/tasks/download_large_file.yml b/roles/maps/tasks/download_large_file.yml
--- a/roles/maps/tasks/download_large_file.yml
+++ b/roles/maps/tasks/download_large_file.yml
@@ -91,23 +91,23 @@
       args:
         executable: /bin/bash
         creates: "{{ dest_path }}"
-    vars:
-      # Where the file eventually goes
-      dest_path: "{{ dest_base_path }}/{{ item }}"
-      log_file: "{{ item }}.log"
-      working_dir: "/library/downloads/maps"
-    rescue:
-      # We output summaries to a log file for the user's benefit,
-      # but all of the errors necessarily show up there as well.
-      # Here, we parse out the error message, ignoring almost all of
-      # the summary lines, which could be a lot.
-      # Finally, we exit 1 so Ansible shows this error.
-      - name: "Error downloading {{ item }}"
-        shell: |
-          set -euo pipefail
+  vars:
+    # Where the file eventually goes
+    dest_path: "{{ dest_base_path }}/{{ item }}"
+    log_file: "{{ item }}.log"
+    working_dir: "/library/downloads/maps"
+  rescue:
+    # We output summaries to a log file for the user's benefit,
+    # but all of the errors necessarily show up there as well.
+    # Here, we parse out the error message, ignoring almost all of
+    # the summary lines, which could be a lot.
+    # Finally, we exit 1 so Ansible shows this error.
+    - name: "Error downloading {{ item }}"
+      shell: |
+        set -euo pipefail
 
-          cd {{ working_dir }}
+        cd {{ working_dir }}
 
-          echo "aria2c error:" 1>&2
-          tac "{{ log_file }}" | sed '/'"Download Progress Summary as of"'/q' | tac 1>&2
-          exit 1
+        echo "aria2c error:" 1>&2
+        tac "{{ log_file }}" | sed '/'"Download Progress Summary as of"'/q' | tac 1>&2
+        exit 1
