scripts/ansible: Interim /etc/pip.conf for "32-bit" RasPiOS 12

diff --git a/scripts/ansible b/scripts/ansible
--- a/scripts/ansible
+++ b/scripts/ansible
@@ -227,6 +227,17 @@ else
     echo -e "\nCreate virtual environment for Ansible"
     python3 -m venv /usr/local/ansible
 
+    # 2023-09-10: Work around #3526 "32-bit" RasPiOS 12 pre-release issue...
+    # 'Package issue: cryptography 41.0.3 leads to cffi 1.15.1 failure on
+    # "32-bit" Raspberry Pi OS [REASON: /etc/pip.conf missing on some Bookworm
+    # pre-releases' == https://github.com/piwheels/packages/issues/390
+    if ! [ -f /etc/pip.conf ] && [ -f /etc/rpi-issue ]; then
+        cat > /etc/pip.conf << EOF
+[global]
+extra-index-url=https://www.piwheels.org/simple
+EOF
+    fi
+
     # "if not ubuntu" (covers RasPiOS & Debian) would also work, but is overbroad:
     # if ! grep -qi ubuntu /etc/os-release; then
     #
