test failure runners2

diff --git a/scripts/ansible b/scripts/ansible
--- a/scripts/ansible
+++ b/scripts/ansible
@@ -290,8 +290,6 @@ EOF
     # - 'apt -y install libffi-dev python3-dev'
     # - painstaking pinning of cryptography or cffi (etc) to older version #s
     /usr/local/ansible/bin/python3 -m pip install --prefer-binary --upgrade ansible-core
-    # test github runners fail without true
-    cp $CWD/collections.yml /usr/local/ansible/ || true
     echo -e "\nCreate symlinks /usr/local/bin/ansible* -> /usr/local/ansible/bin/ansible*"
     cd /usr/local/ansible/bin
     for bin in ansible*; do
@@ -303,10 +301,11 @@ EOF
 # explicit upgrading of collections (--upgrade / -U flag) in version "2.11"
 # with PR ansible/ansible#73336.  See also IIAB PRs #2647 #2652 #2653 #2655.
     echo -e "\n\nIIAB requires these ~4 Ansible Collections: (we upgrade them here if possible!)\n"
+    # test github runners fail without '|| true'
+    cp $CWD/collections.yml /usr/local/ansible/ || true
     cd /usr/local/ansible/
     . bin/activate
-    bin/ansible-galaxy collection install --force-with-deps -r collections.yml -p collections
-    deactivate
+    bin/ansible-galaxy collection install --force-with-deps -r collections.yml -p collections deactivate
 fi
 # But going forward they'll be stored herein: [~24MB for 4 Collections as of 2025-02-18]
 #    /usr/local/ansible/collections/ansible_collections
