port #2523 - exit early on no /etc/os-release

diff --git a/scripts/ansible b/scripts/ansible
--- a/scripts/ansible
+++ b/scripts/ansible
@@ -6,6 +6,7 @@
 APT_PATH=/usr/bin    # Avoids problematic /usr/local/bin/apt on Linux Mint
 CURR_VER="undefined"    # Ansible version you currently have installed
 GOOD_VER="2.10.4"    # Orig for 'yum install [rpm]' & XO laptops (pip install)
+release=bionic
 # We install latest 'ansible-base' from PPA: (may be more recent than GOOD-VER)
 # https://launchpad.net/~ansible/+archive/ubuntu/ansible
 # https://launchpad.net/~ansible/+archive/ubuntu/ansible-2.10
@@ -30,7 +31,11 @@ export DEBIAN_FRONTEND=noninteractive
 
 echo -e "\n\nYOU ARE RUNNING: /opt/iiab/iiab/scripts/ansible (TO INSTALL ANSIBLE)\n"
 #echo -e 'Alternative:     /opt/iiab/iiab/scripts/ansible-2.9.x ("Slow Food")\n'
-release=bionic
+if [ ! -f /etc/debian_version ]; then    # e.g. Raspbian, Ubuntu, Mint & Debian
+    echo -e "\nEXITING: /etc/debian_version FILE NOT FOUND.  Linux OS support info here:"
+    echo -e "           https://github.com/iiab/iiab/wiki/IIAB-Platforms\n"
+    exit 1
+fi
 source /etc/os-release
 # Override bionic to focal for Ubuntu 20.04/20.10/21.04 as python3.8 is the base
 # 18.04 bionic is based on python 3.7
@@ -63,11 +68,6 @@ echo -e "(Internet-in-a-Box requests ansible-base $GOOD_VER or higher)\n"
 
 # Code above designed to work on all Linux distributions, to preserve options,
 # in support of any volunteer(s) wanting to port IIAB to a new Linux/distro.
-if [ ! -f /etc/debian_version ]; then    # e.g. Raspbian, Ubuntu, Mint & Debian
-    echo -e "\nEXITING: /etc/debian_version FILE NOT FOUND.  Linux OS support info here:"
-    echo -e "           https://github.com/iiab/iiab/wiki/IIAB-Platforms\n"
-    exit 1
-fi
 
 echo -e "\napt update; install dirmngr; PPA to /etc/apt/sources.list.d/iiab-ansible.list\n"
 $APT_PATH/apt update
