exit early with no /etc/debian_version present

diff --git a/scripts/ansible b/scripts/ansible
--- a/scripts/ansible
+++ b/scripts/ansible
@@ -10,6 +10,12 @@ GOOD_VER="2.10.6"    # Orig for 'yum install [rpm]' & XO laptops (pip install)
 # We install the latest 'ansible-base' from PPA, using an OS 'CODENAME' below:
 # https://launchpad.net/~ansible/+archive/ubuntu/ansible
 
+if [ ! -f /etc/debian_version ]; then    # e.g. Raspbian, Ubuntu, Mint & Debian
+    echo -e "\nEXITING: /etc/debian_version FILE NOT FOUND.  Linux OS support info here:"
+    echo -e "           https://github.com/iiab/iiab/wiki/IIAB-Platforms\n"
+    exit 1
+fi
+
 # 'lsb_release -sc' gives Mint 20 codename 'ulyana' etc: (TOO FINE-GRAINED)
 if grep -q buster /etc/os-release /etc/debian_version; then
     CODENAME=bionic    # Debian 10, RaspiOS 10 & Buster-like distros
@@ -71,11 +77,6 @@ echo -e "(Internet-in-a-Box requests ansible-base $GOOD_VER or higher)\n"
 
 # Code above designed to work on all Linux distributions, to preserve options,
 # in support of any volunteer(s) wanting to port IIAB to a new Linux/distro.
-if [ ! -f /etc/debian_version ]; then    # e.g. Raspbian, Ubuntu, Mint & Debian
-    echo -e "\nEXITING: /etc/debian_version FILE NOT FOUND.  Linux OS support info here:"
-    echo -e "           https://github.com/iiab/iiab/wiki/IIAB-Platforms\n"
-    exit 1
-fi
 
 echo -e "\napt update; install dirmngr; PPA to /etc/apt/sources.list.d/iiab-ansible.list\n"
 $APT_PATH/apt update
