ordering - exit early

diff --git a/scripts/ansible b/scripts/ansible
--- a/scripts/ansible
+++ b/scripts/ansible
@@ -7,10 +7,18 @@ GOOD_VER="2.9.6"    # For XO laptops (pip install) & CentOS (yum install rpm)
 # https://launchpad.net/~ansible/+archive/ubuntu/ansible
 
 export DEBIAN_FRONTEND=noninteractive
+source /etc/os-release
+if [ $VERSION_CODENAME = "buster" ]; then
+    release=bionic
+elif [ $VERSION_CODENAME = "focal" ]; then
+    release=eoan
+else
+    echo -e "\nEXITING: Could not detect your OS (unsupported?)\n"
+    exit 1
+fi
 
 echo -e "\n\nYOU ARE RUNNING: /opt/iiab/iiab/scripts/ansible (TO INSTALL ANSIBLE)"
 #echo -e 'Alternative:     /opt/iiab/iiab/scripts/ansible-2.8.x ("Slow Food")\n'
-
 echo -e "RECOMMENDED PREREQUISITES:"
 echo -e "(1) Verify you're online"
 echo -e "(2) Remove all prior versions of Ansible using"
@@ -30,20 +38,9 @@ else
     echo -e "(Internet-in-a-Box requests Ansible $GOOD_VER or higher)\n"
 fi
 
-source /etc/os-release
 echo -e "\napt update; install dirmngr; PPA to /etc/apt/sources.list.d/iiab-ansible.list\n"
-
-if [ $VERSION_CODENAME = "buster" ]; then
-    release=bionic
-elif [ $VERSION_CODENAME = "focal" ]; then
-    release=eoan
-else
-    echo -e "\nEXITING: Could not detect your OS (unsupported?)\n"
-    exit 1
-fi
 echo "deb http://ppa.launchpad.net/ansible/ansible/ubuntu "$release" main" \
-> /etc/apt/sources.list.d/iiab-ansible.list
-
+    > /etc/apt/sources.list.d/iiab-ansible.list
 $APT_PATH/apt update
 $APT_PATH/apt -y install dirmngr
 echo -e '\nIF YOU FACE ERROR "signatures couldn'"'"'t be verified because the public key is not available" THEN REPEATEDLY RE-RUN "sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 93C4A3FD7BB9C367"\n'
