lets keep Ubuntu 18,19 alive

diff --git a/scripts/ansible b/scripts/ansible
--- a/scripts/ansible
+++ b/scripts/ansible
@@ -8,14 +8,24 @@ GOOD_VER="2.9.6"    # For XO laptops (pip install) & CentOS (yum install rpm)
 
 export DEBIAN_FRONTEND=noninteractive
 source /etc/os-release
-if [ $VERSION_CODENAME = "buster" ]; then
-    release=bionic
-elif [ $VERSION_CODENAME = "focal" ]; then
-    release=eoan
-else
-    echo -e "\nEXITING: Could not detect your OS (unsupported?)\n"
-    exit 1
-fi
+case $VERSION_CODENAME in
+    buster)
+        release=bionic
+    ;;
+    focal)
+        release=eoan
+    ;;
+    eoan)
+        release=eoan
+    ;;
+    bionic)
+        release=bionic
+    ;;
+   *)
+        echo -e "\nEXITING: Could not detect your OS (unsupported?)\n"
+        exit 1
+    ;;
+esac
 
 echo -e "\n\nYOU ARE RUNNING: /opt/iiab/iiab/scripts/ansible (TO INSTALL ANSIBLE)"
 #echo -e 'Alternative:     /opt/iiab/iiab/scripts/ansible-2.8.x ("Slow Food")\n'
