move completed and OS test exit

diff --git a/scripts/ansible b/scripts/ansible
--- a/scripts/ansible
+++ b/scripts/ansible
@@ -15,6 +15,12 @@ export DEBIAN_FRONTEND=noninteractive
 # Why 'noninteractive' appears needed:
 # https://github.com/iiab/iiab/issues/564#issuecomment-347264985
 
+if [ ! -f /etc/debian_version ]; then    # e.g. Raspbian, Ubuntu, Mint & Debian
+    echo -e "\nEXITING: /etc/debian_version FILE NOT FOUND.  Linux OS support info here:"
+    echo -e "           https://github.com/iiab/iiab/wiki/IIAB-Platforms\n"
+    exit 1
+fi
+
 echo -e "\n\nYOU ARE RUNNING: /opt/iiab/iiab/scripts/ansible (TO INSTALL ANSIBLE)\n"
 #echo -e 'Alternative:     /opt/iiab/iiab/scripts/ansible-2.9.x ("Slow Food")\n'
 
@@ -36,12 +42,6 @@ else
     echo -e "ANSIBLE NOT FOUND ON THIS COMPUTER -- LET'S TRY TO INSTALL IT!"
 fi
 echo -e "(Internet-in-a-Box requests ansible-base $GOOD_VER or higher)\n"
-
-if [ ! -f /etc/debian_version ]; then    # e.g. Raspbian, Ubuntu, Mint & Debian
-    echo -e "\nEXITING: /etc/debian_version FILE NOT FOUND.  Linux OS support info here:"
-    echo -e "           https://github.com/iiab/iiab/wiki/IIAB-Platforms\n"
-    exit 1
-fi
 
 echo -e "\napt update; install dirmngr; PPA to /etc/apt/sources.list.d/iiab-ansible.list\n"
 $APT_PATH/apt update
@@ -72,17 +72,7 @@ $APT_PATH/apt -y --allow-downgrades install ansible-base \
 ansible-galaxy collection install community.general    # Re-running these
 ansible-galaxy collection install community.mysql      # appears to be safe!?
 
-echo -e "\nSUCCESS: verify Ansible using 'ansible --version' and/or 'apt -a list ansible-base'\n\n"
-
-# TEMPORARILY USE ANSIBLE 2.4.4 (REMOVE IT WITH "pip uninstall ansible")
-#pip install ansible==2.4.4
-
-# TEMPORARILY USE ANSIBLE 2.4.2 DUE TO 2.4.3 MEMORY BUG. DETAILS @ https://github.com/iiab/iiab/issues/669
-#echo "Install http://download.iiab.io/packages/ansible_2.4.2.0-1ppa~xenial_all.deb"
-#cd /tmp
-#wget http://download.iiab.io/packages/ansible_2.4.2.0-1ppa~xenial_all.deb
-#apt -y --allow-downgrades install ./ansible_2.4.2.0-1ppa~xenial_all.deb
-
 # Needed?
 mkdir -p /etc/ansible
 echo -e '[local]\nlocalhost\n' > /etc/ansible/hosts
+echo -e "\nSUCCESS: verify Ansible using 'ansible --version' and/or 'apt -a list ansible-base'\n\n"
