70-usb-library.j2: Cleaner logging & error handling (e.g. exit code 1)

diff --git a/roles/usb_lib/templates/mount.d/70-usb-library.j2 b/roles/usb_lib/templates/mount.d/70-usb-library.j2
--- a/roles/usb_lib/templates/mount.d/70-usb-library.j2
+++ b/roles/usb_lib/templates/mount.d/70-usb-library.j2
@@ -31,16 +31,16 @@ logger -t "usb_lib (70-usb-library)" "BOOTFW_DEV is: $BOOTFW_DEV"
 
 if [ "$UM_DEV" == "$LIB_DEV" ]; then
     logger -t "usb_lib (70-usb-library)" "Skipping $UM_MOUNTPOINT containing /library"
-    exit
+    exit 1
 elif [ "$UM_DEV" == "$ROOT_DEV" ]; then
     logger -t "usb_lib (70-usb-library)" "Skipping $UM_MOUNTPOINT containing rootfs"
-    exit
+    exit 1
 elif [ "$UM_DEV" == "$BOOT_DEV" ]; then
     logger -t "usb_lib (70-usb-library)" "Skipping $UM_MOUNTPOINT containing /boot"
-    exit
+    exit 1
 elif [ "$UM_DEV" == "$BOOTFW_DEV" ]; then
     logger -t "usb_lib (70-usb-library)" "Skipping $UM_MOUNTPOINT containing /boot/firmware"
-    exit
+    exit 1
 fi
 
 # 2025-01-25: Check for existence of folder PUBLIC on USB stick: if found, the stick will not be completely browsable.
@@ -55,9 +55,13 @@ else
 fi
 
 CONTENT_LINK_USB=$(basename $UM_MOUNTPOINT | awk '{print toupper($0)}')
+if [ -z "$CONTENT_LINK_USB" ]; then
+    logger -t "usb_lib (70-usb-library)" "ERROR: Var CONTENT_LINK_USB is empty ("rm -rf /library/www/html/local_content/" might be dangerous!)"
+    exit 1
+fi
 CONTENT_LINK="{{ doc_root }}/local_content/$CONTENT_LINK_USB"
-logger -t "usb_lib (70-usb-library)" "Creating link from $CONTENT_LINK to $SHARE_DIR"
 # 'rm -rf' even stronger than 'ln -nsf' and 'ln -Tsf'
 # https://serverfault.com/questions/147787/how-to-update-a-symbolic-link-target-ln-f-s-not-working/522483#522483
+logger -t "usb_lib (70-usb-library)" "Creating link from $CONTENT_LINK to $SHARE_DIR"
 rm -rf $CONTENT_LINK
 ln -s $SHARE_DIR $CONTENT_LINK
