split workflows

diff --git a/.github/workflows/raspios-image.yml b/.github/workflows/raspios-image.yml
--- a/.github/workflows/raspios-image.yml
+++ b/.github/workflows/raspios-image.yml
@@ -1,4 +1,4 @@
-name: 'IIAB LARGE on RPiOS Lite Latest'
+name: 'IIAB image on RPiOS Lite Latest'
 
 # cancel-in-progress: false
 # concurrency:
@@ -22,18 +22,18 @@ jobs:
           #   # https://github.com/marketplace/actions/maximize-build-disk-space-only-remove-unwanted-software#how-it-works
           #   working_image_size: 75000
           #   preset_id: en-medical
-          - edition: large
-            config: vars/local_vars_large.yml
-            working_image_size: 20000
+          #- edition: large
+          #  config: vars/local_vars_large.yml
+          #  working_image_size: 20000
           # - edition: medium
           #   config: vars/local_vars_medium.yml
           #   working_image_size: 15000
           # - edition: small
           #   config: vars/local_vars_small.yml
           #   working_image_size: 15000
-          #- edition: tiny
-          #  config: vars/local_vars_tiny.yml
-          #  working_image_size: 7450
+          - edition: tiny
+            config: vars/local_vars_tiny.yml
+            working_image_size: 7450
     steps:
       - uses: actions/checkout@v6
         with:
@@ -58,6 +58,9 @@ jobs:
           STATE_FILE=$(find . -maxdepth 1 -name "*.state" | head -n 1)
           source "$STATE_FILE"
 
+          echo "VM image is $MOUNT_DIR mounted at:"
+          mount | grep loop
+
           VERSION=$(grep '^iiab_base_ver:' ../iiab/vars/default_vars.yml | awk '{print $2}')
           echo "IIAB_BASE_VERSION=$VERSION" >> $GITHUB_ENV
           DATE=$(date +'%y%m%d')
@@ -76,76 +79,85 @@ jobs:
           echo "rpi_image: True" >> "$MOUNT_DIR/etc/iiab/local_vars.yml"
           sed -i "s/^iiab_admin_user_install: True/iiab_admin_user_install: False/" "$MOUNT_DIR/etc/iiab/local_vars.yml"
 
-          if ! command -v expect &>/dev/null; then
-              apt-get update && apt-get install -y expect
-          fi
-          if ! command -v systemd-nspawn &> /dev/null; then
-              apt-get update && apt-get install -y systemd-container
-          fi
+          #if ! command -v expect &>/dev/null; then
+          #    apt-get update && apt-get install -y expect
+          #fi
+          #if ! command -v systemd-nspawn &> /dev/null; then
+          #    apt-get update && apt-get install -y systemd-container
+          #fi
 
           systemctl is-active --quiet systemd-networkd || systemctl start systemd-networkd
           systemctl is-active --quiet systemd-resolved || systemctl start systemd-resolved
 
           # Explicitly allow forwarding for systemd-nspawn virtual interfaces
-          sysctl -w net.ipv4.ip_forward=1
-          EXT_IF=$(ip route | grep default | awk '{print $5}' | head -n1)
-          iptables -t nat -A POSTROUTING -o "$EXT_IF" -j MASQUERADE
-          iptables -A FORWARD -i ve-+ -o "$EXT_IF" -j ACCEPT
-          iptables -A FORWARD -i "$EXT_IF" -o ve-+ -m state --state RELATED,ESTABLISHED -j ACCEPT
+          #sysctl -w net.ipv4.ip_forward=1
+          #EXT_IF=$(ip route | grep default | awk '{print $5}' | head -n1)
+          #iptables -t nat -A POSTROUTING -o "$EXT_IF" -j MASQUERADE
+          #iptables -A FORWARD -i ve-+ -o "$EXT_IF" -j ACCEPT
+          #iptables -A FORWARD -i "$EXT_IF" -o ve-+ -m state --state RELATED,ESTABLISHED -j ACCEPT
 
           # Manually setting DNS can help avoid host loopback/127.0.0.53 issues
           # echo "nameserver 1.1.1.1" >> "$MOUNT_DIR/etc/resolv.conf"
 
-          sed 's/^          //' << 'EOF_PRESET' > "$MOUNT_DIR/root/install_preset.sh"
+          #sed 's/^          //' << 'EOF_PRESET' > "$MOUNT_DIR/root/install_preset.sh"
+          #!/bin/bash
+          #set -euo pipefail
+          #cd /opt/admin/cmdsrv
+
+          #scripts/get_kiwix_catalog
+          #scripts/get_oer2go_catalog
+
+          #if [ -n "${{ matrix.preset_id }}" ]; then
+          #    iiab-cmdsrv-ctl 'INST-PRESETS {"preset_id":"${{ matrix.preset_id }}"}'
+          #fi
+
+          #rm -f /root/install_preset.sh
+          #EOF_PRESET
+          #chmod +x "$MOUNT_DIR/root/install_preset.sh"
+
+          #systemd-firstboot --root="$MOUNT_DIR" --delete-root-password --force
+          #export MOUNT_DIR
+          #sed 's/^          //' << 'EXPECT_EOF' | expect
+          #set timeout 7200
+
+          #spawn systemd-nspawn -q --network-veth --resolv-conf=off -D $env(MOUNT_DIR) -M box --boot
+          mount --bind /dev "${MOUNT_DIR}"/dev
+          mount -t proc none "${MOUNT_DIR}"/proc
+          mount -t sysfs none "${MOUNT_DIR}"/sys
+          mount -t devpts none "${MOUNT_DIR}"/dev/pts
+          mount -t tmpfs tmpfs "${MOUNT_DIR}"/run
+          mount -t tmpfs tmpfs "${MOUNT_DIR}"/tmp
+
+          sed 's/^          //' << 'EOF_CHROOT' > "$MOUNT_DIR/root/builder.sh"
           #!/bin/bash
           set -euo pipefail
-          cd /opt/admin/cmdsrv
 
-          scripts/get_kiwix_catalog
-          scripts/get_oer2go_catalog
+          export DEBIAN_FRONTEND=noninteractive
 
-          if [ -n "${{ matrix.preset_id }}" ]; then
-              iiab-cmdsrv-ctl 'INST-PRESETS {"preset_id":"${{ matrix.preset_id }}"}'
-          fi
+          apt update
+          mkdir -p /etc/initramfs-tools/conf.d
+          echo 'MODULES=most' > /etc/initramfs-tools/conf.d/nspawn.conf
+          apt -y upgrade
 
-          rm -f /root/install_preset.sh
-          EOF_PRESET
-          chmod +x "$MOUNT_DIR/root/install_preset.sh"
+          apt install curl
+          curl -fLo /usr/sbin/iiab https://raw.githubusercontent.com/iiab/iiab-factory/master/iiab
+          chmod 0755 /usr/sbin/iiab
+          /usr/sbin/iiab --risky
 
-          systemd-firstboot --root="$MOUNT_DIR" --delete-root-password --force
-          export MOUNT_DIR
-          sed 's/^          //' << 'EXPECT_EOF' | expect
-          set timeout 7200
+          usermod --lock --expiredate=1 root
+          EOF_CHROOT
 
-          spawn systemd-nspawn -q --network-veth --resolv-conf=off -D $env(MOUNT_DIR) -M box --boot
-          expect "login: " { send "root\r" }
+          chmod 0755 $MOUNT_DIR/root/builder.sh
+          chroot $MOUNT_DIR /root/builder.sh
+          # could clean up builder at this point
 
-          expect -re {#\s?$} { send "apt update\r" }
-          expect -re {#\s?$} { send "mkdir -p /etc/initramfs-tools/conf.d && echo 'MODULES=most' > /etc/initramfs-tools/conf.d/nspawn.conf\r" }
-          expect -re {#\s?$} { send "DEBIAN_FRONTEND=noninteractive apt upgrade -y\r" }
+          umount "${MOUNT_DIR}"/run
+          umount "${MOUNT_DIR}"/tmp
+          umount "${MOUNT_DIR}"/dev/pts
+          umount "${MOUNT_DIR}"/dev
+          umount "${MOUNT_DIR}"/sys
+          umount "${MOUNT_DIR}"/proc
 
-          expect -re {#\s?$} { send "curl -fLo /usr/sbin/iiab https://raw.githubusercontent.com/iiab/iiab-factory/master/iiab\r" }
-          expect -re {#\s?$} { send "chmod 0755 /usr/sbin/iiab\r" }
-          expect -re {#\s?$} { send "/usr/sbin/iiab --risky\r" }
-          expect {
-              timeout { puts "\nTimed out waiting for final confirmation prompt"; exit 1 }
-              "photographed" { send "\r" }
-          }
-          # forced reboot
-          expect "login: " { send "root\r" }
-
-          expect -re {#\s?$} { send "/root/install_preset.sh\r" }
-
-          expect -re {#\s?$} { send "usermod --lock --expiredate=1 root\r" }
-
-          # legacy whiptail TUI OOBE, replaced by cloud-init / rpi-imager
-          # expect -re {#\s?$} { send "systemctl disable userconfig.service\r" }
-
-          expect -re {#\s?$} { send "shutdown now\r" }
-          expect eof
-          EXPECT_EOF
-
-          EOF
 
       - name: Validation
         working-directory: nspawn-loop
